version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  #This is the production version.
  script: python_code.web_app_mains.main.app
  #
  #This is the uses the production code but the with the debug flag in the
  #webapp set to True.
  #script: python_code.web_app_mains.main_debug.app
  #
  #Used for debugging, this does not charge but does add to the ticket list.
  #script: python_code.web_app_mains.main_dummy_charge.app
  #
  #Used for debugging, this has no error handling for the charge. Thus errors
  #are tranparrent.
  #script: python_code.web_app_mains.main_charge_with_no_error_handling.app

  secure: always

# Use actual version number
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
